#!/bin/bash
if [[ $1 != server ]] && [[ $1 != client ]]
then
  echo "usage build <client/server>"
  exit
fi

source ./.getenv
APP_NAME=${1:-APP_NAME}
BUILD_CONTEXT=$APP_NAME
DOCKER_FILE=$APP_NAME/Dockerfile
IMAGE_REPO_NAME=$APP_NAME

echo APP_NAME = $APP_NAME
echo BUILD_CONTEXT = $BUILD_CONTEXT
echo BUILD_FILE = $BUILD_FILE
echo IMAGE_REPO_NAME = $IMAGE_REPO_NAME

if [[ $1 == "-n" ]]
then
  echo "Please enter 'y' to continue..."
  read answer
  [[ $answer != "y" ]] && exit 0
else
  $BUILD_FILE
fi

