version: "3.8"

services:
  client:
    image: client
    environment:
      - name=value
    depends_on:
      - server
    ports:
      - 3000:80
  server:
    image: server
    ports:
      - 4000:3030
    environment:
      - TYPEORM_HOST=db
      - REDIS_PASSWORD=redispass
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass12
      - POSTGRES_DB=pgdb
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:5
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
volumes:
  db-data:
