name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Server Install modules
      run: yarn --cwd server
    - name: Server Run tests
      run: yarn --cwd server test
