name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Client Install modules
      run: yarn --cwd client
    - name: Client Run tests
      run: yarn --cwd test